# Site settings
title: Arian Shahrizad
description: Developer of Things
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arian Shahrizad
user_description: I specialize in in backend infrastructure/scalability, databases, and tech strategy.
user_title: Software Engineer and Solutions Architect
email: arianshahrizad@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
